version: '3.9'

services:
  webcontainer:
    image: tomcat:latest
    container_name: webcontainer
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: abhishek
      MYSQL_DATABASE: library
    ports:
      - "3306:3306"
